# Generated by Django 4.0.4 on 2022-04-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='user',
        ),
    ]
