# Generated by Django 4.0.4 on 2022-04-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubsub',
            old_name='pubs',
            new_name='user',
        ),
    ]
