# Generated by Django 4.0.4 on 2022-04-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_master', '0002_rename_author_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='subscribers_for',
            field=models.BooleanField(default=True, verbose_name='Только для подписчиков'),
        ),
    ]
