# Generated by Django 4.0.4 on 2022-04-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_master', '0003_todo_subscribers_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='subscribers_for',
            new_name='private',
        ),
    ]
